### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by KrzysztofMadejski** [themoonsheep/project-template#2]
Error:
```
$ python manage.py migrate
.....
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

Looks like your Python was not compiled with sqlite support. Check https://stackoverflow.com/a/24449632/803174 and https://stackoverflow.com/questions/42766063/python3-6-import-sqlite3-error for more info.

On Ubuntu 17.04 try using python3.5 instead of 3.6. (worked for me).

**Comment by menyagah** [comment]
Hello.
I hope this helps someone.

- I was having the following error using  **'sqllite'** which I believe could be a typo:
**sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite**

Also I was using python 3.6 and got the following error:
**from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'**

- so i changed my environment from python3.6 to python3.5 and changed my URI to this:

**app.config['SQLALCHEMY_DATABASE_URI']='sqlite:////home/martin/code/Python/Flask/database.db'**
everything worked well after..
